// ============================================================================
// Barmaj Server — Arduino Compilation Backend
// ============================================================================
// This Express server accepts Arduino C++ source code (generated by the Barmaj
// front-end transpiler), compiles it using arduino-cli, and returns the
// resulting .hex binary as a base64-encoded string.
//
// Endpoints:
//   POST /compile   — compile Arduino code → return .hex (base64)
//   GET  /health    — simple health-check
//
// Prerequisites:
//   1. Install arduino-cli:  https://arduino.github.io/arduino-cli/
//   2. Install the AVR core: arduino-cli core install arduino:avr
//   3. npm install && npm start
// ============================================================================

const express = require('express');
const cors = require('cors');
const { v4: uuidv4 } = require('uuid');
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

// ---------------------------------------------------------------------------
// 1.  CONFIGURATION
// ---------------------------------------------------------------------------

const PORT = process.env.PORT || 3001;

// Compile timeout in milliseconds.
// arduino-cli can be very slow on the first compile for a given board because
// it builds the entire core library from scratch and caches it.  Subsequent
// compiles are much faster (~5-10s).  60 seconds is generous enough for the
// first compile on slow machines.
const COMPILE_TIMEOUT = 120000;

// Board FQBN (Fully Qualified Board Name) mapping.
// The front-end sends a short board identifier; we map it to the exact FQBN
// string that arduino-cli expects.
const BOARD_FQBN = {
  uno:        'arduino:avr:uno',
  nano:       'arduino:avr:nano:cpu=atmega328',
  mega:       'arduino:avr:mega',
  unor4wifi:  'arduino:renesas_uno:unor4wifi',
};

// Boards that require server-side upload (non-AVR boards).
// AVR boards use client-side avrbro flashing via Web Serial.
// Non-AVR boards need arduino-cli upload on the server.
const SERVER_UPLOAD_BOARDS = new Set(['unor4wifi']);

// Base directory for temporary sketch folders.
// IMPORTANT: We use os.tmpdir() which returns a short path on Windows
// (e.g. C:\Users\FAISA~1\AppData\Local\Temp) — this avoids issues with
// spaces in paths that can break arduino-cli.
const TEMP_BASE = path.join(os.tmpdir(), 'barmaj-compile');

// ---------------------------------------------------------------------------
// 2.  EXPRESS APP SETUP
// ---------------------------------------------------------------------------

const app = express();

// Parse incoming JSON request bodies (Arduino sketches can be large,
// so we allow up to 1 MB — well above typical sketch sizes).
app.use(express.json({ limit: '1mb' }));

// Enable CORS — allow origins listed in CORS_ORIGINS env var (comma-separated).
// Falls back to localhost:3000 for local development.
const allowedOrigins = process.env.CORS_ORIGINS
  ? process.env.CORS_ORIGINS.split(',').map(o => o.trim())
  : ['http://localhost:3000'];

app.use(cors({
  origin: function (origin, callback) {
    if (!origin) return callback(null, true); // allow curl / health checks
    if (allowedOrigins.includes(origin)) return callback(null, true);
    callback(new Error('Not allowed by CORS'));
  },
}));

// ---------------------------------------------------------------------------
// 3.  HELPER — Run a shell command and return a Promise
// ---------------------------------------------------------------------------
// Wraps child_process.exec in a Promise so we can use async/await.
// Resolves with { stdout, stderr } on success (exit code 0).
// Rejects with an error that includes stdout + stderr on failure.
// Uses COMPILE_TIMEOUT to give arduino-cli enough time on first compile.

function run(command, options = {}) {
  return new Promise((resolve, reject) => {
    exec(command, { timeout: COMPILE_TIMEOUT, ...options }, (error, stdout, stderr) => {
      if (error) {
        // Attach stdout/stderr to the error object so callers can inspect
        // compiler output even when the process exits non-zero.
        error.stdout = stdout;
        error.stderr = stderr;
        return reject(error);
      }
      resolve({ stdout, stderr });
    });
  });
}

// ---------------------------------------------------------------------------
// 4.  HELPER — Clean up a temporary sketch directory
// ---------------------------------------------------------------------------
// Recursively removes the sketch folder and all its contents.
// Uses fs.rmSync with { recursive: true, force: true } for reliability
// on Windows where async delete can race with antivirus file locks.

function cleanup(dirPath) {
  try {
    fs.rmSync(dirPath, { recursive: true, force: true });
  } catch (err) {
    // Swallow errors — cleanup is best-effort.  If the OS temp directory
    // cleaner gets it later, that's fine too.
    console.warn('  [cleanup] Could not remove temp dir:', err.message);
  }
}

// ---------------------------------------------------------------------------
// 5.  HELPER — Locate the compiled binary file (.hex or .bin)
// ---------------------------------------------------------------------------
// arduino-cli writes the compiled binary into the output directory.
// AVR boards produce .hex files; ARM boards (like R4 WiFi) produce .bin files.
//
// We first check the expected path pattern, then fall back to a recursive
// search for any .hex or .bin file in the output directory.

function findBinaryFile(dir) {
  // Guard: if the directory doesn't exist, return null immediately.
  if (!fs.existsSync(dir)) return null;

  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        const found = findBinaryFile(fullPath);
        if (found) return found;
      } else if (entry.name.endsWith('.hex') || entry.name.endsWith('.bin')) {
        return fullPath;
      }
    }
  } catch (err) {
    console.warn('  [findBinary] Error scanning directory:', err.message);
  }
  return null;
}

// ---------------------------------------------------------------------------
// 5b.  HELPER — Auto-detect Arduino port using arduino-cli
// ---------------------------------------------------------------------------
// Runs `arduino-cli board list --format json` and finds a connected board
// matching the given FQBN.  Returns the port address (e.g. "COM3") or null.

async function detectPort(fqbn) {
  try {
    const { stdout } = await run('arduino-cli board list --format json');
    const boards = JSON.parse(stdout);

    // arduino-cli v0.35+ returns { detected_ports: [...] }
    const ports = boards.detected_ports || boards;

    for (const entry of ports) {
      const matching = entry.matching_boards || [];
      for (const board of matching) {
        if (board.fqbn === fqbn) {
          return entry.port?.address || entry.address || null;
        }
      }
    }
  } catch (err) {
    console.warn('  [detectPort] Failed to detect port:', err.message);
  }
  return null;
}

// ---------------------------------------------------------------------------
// 6.  ENDPOINT — GET /health
// ---------------------------------------------------------------------------
// Simple health-check endpoint.  Returns HTTP 200 with a JSON status so
// monitoring tools (and the front-end) can verify the server is alive.

app.get('/health', (_req, res) => {
  res.json({ status: 'ok' });
});

// ---------------------------------------------------------------------------
// 7.  ENDPOINT — POST /compile
// ---------------------------------------------------------------------------
// Main compilation endpoint.
//
// Request body (JSON):
//   {
//     code:  string   — the full Arduino C++ source code
//     board: string   — 'uno' | 'nano' | 'mega' (default: 'uno')
//   }
//
// Success response:
//   { success: true, hex: "<base64-encoded .hex file>" }
//
// Error response:
//   { success: false, error: "<compiler error message>" }
//
// Flow:
//   1. Validate the request body.
//   2. Create a temporary sketch folder (arduino-cli requires the .ino file
//      to live inside a folder with the same name as the sketch).
//   3. Write the code to <sketchDir>/<sketchName>.ino.
//   4. Run arduino-cli compile with the appropriate FQBN.
//   5. Find and read the resulting .hex file.
//   6. Return it as base64.
//   7. Clean up the temp folder after sending the response.

app.post('/compile', async (req, res) => {
  // ---- 7a. Validate request body ----
  const { code, board = 'uno' } = req.body;

  if (!code || typeof code !== 'string') {
    return res.status(400).json({
      success: false,
      error: 'Missing or invalid "code" field — expected a non-empty string.',
    });
  }

  const fqbn = BOARD_FQBN[board];
  if (!fqbn) {
    return res.status(400).json({
      success: false,
      error: `Unknown board "${board}". Supported boards: ${Object.keys(BOARD_FQBN).join(', ')}`,
    });
  }

  // ---- 7b. Create a temporary sketch folder ----
  // arduino-cli requires the directory name to match the .ino filename,
  // so we generate a unique name like "sketch_<uuid>".
  // We keep the name short and ASCII-only to avoid Windows path issues.
  const sketchName = `sketch_${uuidv4().slice(0, 8)}`;
  const sketchDir = path.join(TEMP_BASE, sketchName);
  const sketchFile = path.join(sketchDir, `${sketchName}.ino`);

  // Build output directory — kept inside the sketch folder so cleanup
  // removes everything in one shot.
  const outputDir = path.join(sketchDir, 'build');

  console.log(`\n  [compile] Received compile request (board: ${board})`);
  console.log(`  [compile] Sketch dir: ${sketchDir}`);

  try {
    // Ensure the base temp directory and the sketch subdirectory exist.
    await fs.promises.mkdir(sketchDir, { recursive: true });

    // ---- 7c. Write the Arduino source code to the .ino file ----
    await fs.promises.writeFile(sketchFile, code, 'utf-8');
    console.log(`  [compile] Wrote ${code.length} chars to ${sketchName}.ino`);

    // ---- 7d. Compile with arduino-cli ----
    // --output-dir tells arduino-cli to place all build artifacts (including
    // the .hex) inside our output folder, making it easy to find.
    //
    // WINDOWS NOTE: We quote paths to handle any spaces.  The TEMP_BASE
    // path is from os.tmpdir() which is usually safe, but quoting is
    // defensive against edge cases.
    const command = [
      'arduino-cli',
      'compile',
      '--fqbn', fqbn,
      '--output-dir', `"${outputDir}"`,
      `"${sketchDir}"`,
    ].join(' ');

    console.log(`  [compile] Compiling sketch...`);
    console.log(`  [compile] Command: ${command}`);

    const { stderr } = await run(command);

    // Log any compiler warnings (they go to stderr even on success).
    if (stderr && stderr.trim()) {
      console.log(`  [compile] Compiler stderr: ${stderr.trim().slice(0, 200)}`);
    }

    // ---- 7e. Find and read the .hex file ----
    // First try the expected path pattern, then fall back to recursive search.
    let hexPath = path.join(outputDir, `${sketchName}.ino.hex`);
    if (!fs.existsSync(hexPath)) {
      // R4 WiFi produces .bin, not .hex — also check for that
      hexPath = path.join(outputDir, `${sketchName}.ino.bin`);
    }
    if (!fs.existsSync(hexPath)) {
      console.log(`  [compile] Expected binary not found, searching recursively in: ${outputDir}`);
      hexPath = findBinaryFile(outputDir);
    }

    // If still not found, also search the entire sketch directory
    // (some arduino-cli versions put the binary next to the .ino).
    if (!hexPath) {
      console.log(`  [compile] Searching recursively in: ${sketchDir}`);
      hexPath = findBinaryFile(sketchDir);
    }

    if (!hexPath) {
      console.log(`  [compile] ERROR: No binary file found anywhere in ${sketchDir}`);
      return res.json({
        success: false,
        error: 'Compilation succeeded but no .hex file was found in the output.',
      });
    }

    console.log(`  [compile] Found hex at: ${hexPath}`);

    // ---- 7f. Read and encode the hex file ----
    const hexContent = fs.readFileSync(hexPath);
    const hexBase64 = Buffer.from(hexContent).toString('base64');

    console.log(`  [compile] Compilation successful, hex size: ${hexContent.length} bytes`);
    console.log(`  [compile] Sending hex to client... (base64 length: ${hexBase64.length})`);

    // ---- 7g. Return the compiled hex ----
    res.json({
      success: true,
      hex: hexBase64,
    });

  } catch (err) {
    // ---- 7h. Handle compilation errors ----
    // arduino-cli writes compiler errors to stderr.  We extract the most
    // useful information and send it back to the front-end.
    const compilerOutput = err.stderr || err.stdout || err.message;
    console.log(`  [compile] ERROR: ${compilerOutput.slice(0, 300)}`);

    res.json({
      success: false,
      error: compilerOutput,
    });

  } finally {
    // ---- 7i. Always clean up temp files ----
    // We clean up synchronously after the response is sent to avoid
    // race conditions on Windows with file locks.
    console.log(`  [compile] Cleaning up temp dir: ${sketchDir}`);
    cleanup(sketchDir);
  }
});

// ---------------------------------------------------------------------------
// 8.  ENDPOINT — POST /compile-upload
// ---------------------------------------------------------------------------
// Combined compile + upload endpoint for non-AVR boards (R4 WiFi, etc.).
// These boards cannot be flashed from the browser with avrbro, so the server
// handles both compilation and upload using arduino-cli.
//
// Request body (JSON):
//   { code: string, board: string }
//
// Flow:
//   1. Compile the sketch (same as /compile)
//   2. Auto-detect the board's serial port
//   3. Run arduino-cli upload to flash the board
//   4. Return success or error

app.post('/compile-upload', async (req, res) => {
  // R4 WiFi upload requires a physical USB connection to the server machine.
  // On a remote/cloud deployment this is impossible, so we return a clear error.
  if (process.env.REMOTE_DEPLOY === 'true') {
    return res.json({ success: false, error: 'REMOTE_SERVER_NO_USB' });
  }

  const { code, board = 'unor4wifi' } = req.body;

  if (!code || typeof code !== 'string') {
    return res.status(400).json({
      success: false,
      error: 'Missing or invalid "code" field.',
    });
  }

  const fqbn = BOARD_FQBN[board];
  if (!fqbn) {
    return res.status(400).json({
      success: false,
      error: `Unknown board "${board}". Supported: ${Object.keys(BOARD_FQBN).join(', ')}`,
    });
  }

  const sketchName = `sketch_${uuidv4().slice(0, 8)}`;
  const sketchDir = path.join(TEMP_BASE, sketchName);
  const sketchFile = path.join(sketchDir, `${sketchName}.ino`);
  const outputDir = path.join(sketchDir, 'build');

  console.log(`\n  [compile-upload] Board: ${board}, FQBN: ${fqbn}`);

  try {
    // ---- Step 1: Compile ----
    await fs.promises.mkdir(sketchDir, { recursive: true });
    await fs.promises.writeFile(sketchFile, code, 'utf-8');
    console.log(`  [compile-upload] Wrote ${code.length} chars`);

    const compileCmd = [
      'arduino-cli', 'compile',
      '--fqbn', fqbn,
      '--output-dir', `"${outputDir}"`,
      `"${sketchDir}"`,
    ].join(' ');

    console.log(`  [compile-upload] Compiling...`);
    await run(compileCmd);
    console.log(`  [compile-upload] Compilation successful`);

    // ---- Step 2: Detect port ----
    console.log(`  [compile-upload] Detecting port...`);
    const port = await detectPort(fqbn);
    if (!port) {
      return res.json({
        success: false,
        error: `لم يتم العثور على لوحة ${board} متصلة. تأكد من توصيل الأردوينو بكابل USB.`,
      });
    }
    console.log(`  [compile-upload] Found port: ${port}`);

    // ---- Step 3: Upload ----
    console.log(`  [compile-upload] Uploading...`);
    const uploadCmd = [
      'arduino-cli', 'upload',
      '--fqbn', fqbn,
      '-p', port,
      '--input-dir', `"${outputDir}"`,
    ].join(' ');

    await run(uploadCmd);
    console.log(`  [compile-upload] Upload successful!`);

    res.json({ success: true });

  } catch (err) {
    const errorOutput = err.stderr || err.stdout || err.message;
    console.log(`  [compile-upload] ERROR: ${errorOutput.slice(0, 300)}`);
    res.json({ success: false, error: errorOutput });
  } finally {
    cleanup(sketchDir);
  }
});

// ---------------------------------------------------------------------------
// 9.  START THE SERVER
// ---------------------------------------------------------------------------

app.listen(PORT, () => {
  console.log(`\n  ╔══════════════════════════════════════════╗`);
  console.log(`  ║   Barmaj Server running on port ${PORT}      ║`);
  console.log(`  ╚══════════════════════════════════════════╝\n`);
  console.log(`  POST /compile   — compile Arduino sketch`);
  console.log(`  GET  /health    — health check`);
  console.log(`  Temp dir:       ${TEMP_BASE}`);
  console.log(`  Compile timeout: ${COMPILE_TIMEOUT / 1000}s\n`);
});
